[package]
name = "cargo-bug2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-bug-poc = { version = "0.1.0", default-features = false, features=["solana_1_9"], path = "../lib" }